(ns ai.miniforge.phase.verify-test
  "Tests for the verify phase interceptor.

  Generated by miniforge during the meta-meta loop bootstrap session.
  This demonstrates miniforge generating tests for code that miniforge itself created."
  (:require
   [clojure.test :refer [deftest testing is]]
   [ai.miniforge.phase.verify :as verify]
   [ai.miniforge.phase.registry :as registry]
   [ai.miniforge.agent.tester :as tester]
   [ai.miniforge.agent.interface :as agent]))

;------------------------------------------------------------------------------ Test fixtures

(def mock-code-artifact
  {:code/id (random-uuid)
   :code/files [{:path "src/example.clj"
                 :content "(ns example)\n(defn hello [] \"world\")"
                 :action :create}]
   :code/language "clojure"})

(def mock-test-artifact
  {:test/id (random-uuid)
   :test/files [{:path "test/example_test.clj"
                 :content "(ns example-test (:require [clojure.test :refer :all]))\n(deftest t (is true))"}]
   :test/type :unit
   :test/coverage {:lines 85.0 :branches 80.0 :functions 90.0}
   :test/framework "clojure.test"
   :test/assertions-count 10
   :test/cases-count 5})

(defn- mock-tester-agent
  "Create a mock tester agent that returns success."
  []
  (tester/create-tester {}))

(defn- create-base-context
  "Create base context for testing."
  []
  {:execution/input {:description "Test task"
                     :title "Test"
                     :intent "testing"}
   :execution/metrics {:tokens 0 :duration-ms 0}})

;------------------------------------------------------------------------------ Layer 0: Defaults tests

(deftest default-config-test
  (testing "default config has correct structure"
    (is (= :tester (:agent verify/default-config)))
    (is (= [:tests-pass :coverage] (:gates verify/default-config)))
    (is (map? (:budget verify/default-config)))
    (is (= 15000 (get-in verify/default-config [:budget :tokens])))
    (is (= 3 (get-in verify/default-config [:budget :iterations])))
    (is (= 300 (get-in verify/default-config [:budget :time-seconds])))))

(deftest phase-defaults-registration-test
  (testing "verify phase defaults are registered"
    (let [defaults (registry/phase-defaults :verify)]
      (is (some? defaults))
      (is (= :tester (:agent defaults)))
      (is (= [:tests-pass :coverage] (:gates defaults))))))

;------------------------------------------------------------------------------ Layer 1: Interceptor enter tests

(deftest enter-verify-basic-test
  (testing "enter-verify sets up phase context correctly"
    (with-redefs [tester/create-tester (fn [_] (mock-tester-agent))
                  agent/invoke (fn [_ _ _]
                                {:success true
                                 :output mock-test-artifact
                                 :metrics {:tokens 100 :duration-ms 500}})]
      (let [ctx (-> (create-base-context)
                    (assoc-in [:execution/phase-results :implement]
                              {:result {:status :success
                                        :output mock-code-artifact}}))
            ctx-with-config (assoc ctx :phase-config {:phase :verify})
            result (#'verify/enter-verify ctx-with-config)]

        (testing "phase metadata is set"
          (is (= :verify (get-in result [:phase :name])))
          (is (= :tester (get-in result [:phase :agent])))
          (is (= [:tests-pass :coverage] (get-in result [:phase :gates])))
          (is (= :running (get-in result [:phase :status])))
          (is (number? (get-in result [:phase :started-at]))))

        (testing "budget is set from defaults"
          (is (= 15000 (get-in result [:phase :budget :tokens])))
          (is (= 3 (get-in result [:phase :budget :iterations]))))

        (testing "result is stored"
          (is (= mock-test-artifact (get-in result [:phase :result :output]))))))))

(deftest enter-verify-with-code-from-implement-test
  (testing "enter-verify retrieves code from implement phase result"
    (with-redefs [tester/create-tester (fn [_] (mock-tester-agent))
                  agent/invoke (fn [_agent task _ctx]
                                ;; CRITICAL: Verify the task structure matches tester agent expectations
                                ;; This test caught the bug where verify.clj was passing :task/code
                                ;; instead of :code to the tester agent
                                (is (= mock-code-artifact (:code task)))
                                {:success true
                                 :output mock-test-artifact
                                 :metrics {:tokens 200 :duration-ms 600}})]
      (let [ctx (-> (create-base-context)
                    ;; Mock the phase result structure as stored by workflow runner
                    (assoc-in [:execution/phase-results :implement]
                              {:result {:status :success
                                        :output mock-code-artifact}})
                    (assoc :phase-config {:phase :verify}))
            result (#'verify/enter-verify ctx)]
        (is (= mock-test-artifact (get-in result [:phase :result :output])))))))

(deftest enter-verify-with-direct-code-artifact-test
  (testing "enter-verify accepts direct code-artifact in input (test-only workflow)"
    (with-redefs [tester/create-tester (fn [_] (mock-tester-agent))
                  agent/invoke (fn [_agent task _ctx]
                                (is (= mock-code-artifact (:code task)))
                                {:success true
                                 :output mock-test-artifact
                                 :metrics {:tokens 150 :duration-ms 450}})]
      (let [ctx (-> (create-base-context)
                    (assoc-in [:execution/input :task/code-artifact] mock-code-artifact)
                    (assoc :phase-config {:phase :verify}))
            result (#'verify/enter-verify ctx)]
        (is (= mock-test-artifact (get-in result [:phase :result :output])))))))

(deftest enter-verify-with-exception-test
  (testing "enter-verify handles agent exceptions gracefully"
    (with-redefs [tester/create-tester (fn [_] (mock-tester-agent))
                  agent/invoke (fn [_ _ _]
                                (throw (ex-info "Test generation failed"
                                               {:reason :llm-timeout})))]
      (let [ctx (-> (create-base-context)
                    (assoc-in [:execution/input :code-artifact] mock-code-artifact)
                    (assoc :phase-config {:phase :verify}))
            result (#'verify/enter-verify ctx)]
        (is (= false (get-in result [:phase :result :success])))
        (is (= "Test generation failed" (get-in result [:phase :result :error :message])))
        (is (= 0 (get-in result [:phase :result :metrics :tokens])))))))

;------------------------------------------------------------------------------ Rich Comment
(comment
  (clojure.test/run-tests 'ai.miniforge.phase.verify-test)
  :leave-this-here)
