;; Title: Miniforge.ai
;; Copyright 2025-2026 Christopher Lester (christopher@miniforge.ai)
;; Licensed under the Apache License, Version 2.0

(ns ai.miniforge.cli.main.commands.init
  "Init command — analyze a repository and write .miniforge/config.edn."
  (:require
   [babashka.fs :as fs]
   [clojure.pprint :as pprint]
   [ai.miniforge.cli.main.display :as display]
   [ai.miniforge.cli.repo-analyzer :as analyzer]))

;------------------------------------------------------------------------------ Layer 0
;; Config file generation

(def ^:private config-dir ".miniforge")
(def ^:private config-file "config.edn")
(def ^:private config-path (str config-dir "/" config-file))

(defn- format-config
  "Format a repo config map as pretty-printed EDN with a header comment."
  [config]
  (str ";; Miniforge repository configuration\n"
       ";; Generated by `bb miniforge init` — edit as needed.\n"
       ";; See: work/repo-config-profile.spec.edn\n\n"
       (with-out-str (pprint/pprint config))))

(defn- build-config
  "Build the .miniforge/config.edn map from analysis results."
  [analysis]
  (cond-> {:repo/languages    (:languages analysis)
           :repo/frameworks   (:frameworks analysis)
           :repo/build-systems (:build-systems analysis)
           :repo/packs        (:packs analysis)}
    (:git-host analysis)
    (assoc :repo/host (:git-host analysis))))

;------------------------------------------------------------------------------ Layer 1
;; Init execution

(defn- print-analysis
  "Print the analysis results to the user."
  [analysis]
  (display/print-info (str "  Languages:    " (pr-str (:languages analysis))))
  (display/print-info (str "  Frameworks:   " (pr-str (:frameworks analysis))))
  (display/print-info (str "  Build systems: " (pr-str (:build-systems analysis))))
  (display/print-info (str "  Git host:     " (or (:git-host analysis) "unknown")))
  (display/print-info (str "  Packs:        " (pr-str (:packs analysis)))))

(defn- write-config!
  "Write the config file. Returns the path written."
  [repo-path config]
  (let [dir  (fs/path repo-path config-dir)
        path (fs/path repo-path config-path)]
    (fs/create-dirs dir)
    (spit (str path) (format-config config))
    (str path)))

;------------------------------------------------------------------------------ Layer 2
;; Command entry point

(defn init-cmd
  "CLI entry point for the init command."
  [opts]
  (let [repo-path (get opts :repo (str (fs/cwd)))]
    (cond
      (not (fs/exists? repo-path))
      (display/print-error (str "Repository not found: " repo-path))

      :else
      (do
        (display/print-info (str "Analyzing " repo-path " ..."))
        (let [analysis (analyzer/analyze-repo repo-path)
              config   (build-config analysis)
              exists?  (fs/exists? (fs/path repo-path config-path))]

          (print-analysis analysis)

          (when exists?
            (display/print-info (str "  Existing config at " config-path " will be overwritten.")))

          (let [written (write-config! repo-path config)]
            (display/print-info (str "Wrote " written))))))))
