;; Title: Miniforge.ai
;; Subtitle: An agentic SDLC / fleet-control platform
;; Author: Christopher Lester
;; Line: Founder, Miniforge.ai (project)
;; Copyright 2025-2026 Christopher Lester (christopher@miniforge.ai)
;;
;; Licensed under the Apache License, Version 2.0 (the "License");
;; you may not use this file except in compliance with the License.
;; You may obtain a copy of the License at
;;
;;     http://www.apache.org/licenses/LICENSE-2.0
;;
;; Unless required by applicable law or agreed to in writing, software
;; distributed under the License is distributed on an "AS IS" BASIS,
;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;; See the License for the specific language governing permissions and
;; limitations under the License.
(ns ai.miniforge.compliance-scanner.execute-pr-doc
  "PR documentation rendering, split out of `execute` (rule 210: a fifth
   real layer there is the signal to split it).

   Layer 0: Date/table-row formatting + PR-doc file write (pure/I/O)
   Layer 1: PR documentation markdown + GitHub PR body builders"
  (:require [clojure.java.io :as io]
            [clojure.string  :as str]))

;------------------------------------------------------------------------------ Layer 0

(defn ^{:stratum 0} today-str
  "Return today's date as YYYY-MM-DD."
  []
  (str (java.time.LocalDate/now)))

(defn- ^{:stratum 0} format-violation-line
  "Format a single violation as a markdown table row."
  [v]
  (str "| `" (get v :file "") "` | " (get v :line 0)
       " | `" (get v :current "") "`"
       " | " (if-let [s (get v :suggested)] (str "`" s "`") "")
       " |"))

(defn ^{:stratum 0} write-pr-doc!
  "Write the PR documentation file. Creates parent directories if needed.
   Returns the relative path written."
  [repo-path relative-path content]
  (let [f (io/file repo-path relative-path)]
    (io/make-parents f)
    (spit f content)
    relative-path))

;------------------------------------------------------------------------------ Layer 1

(defn ^{:stratum 1} pr-doc-filename
  "Generate the docs/pull-requests/ filename for a compliance PR."
  [category title]
  (let [slug (-> (str/lower-case title)
                 (str/replace #"[^a-z0-9]+" "-")
                 (str/replace #"-+$" ""))]
    (str "docs/pull-requests/" (today-str) "-fix-" category "-" slug ".md")))

(defn ^{:stratum 1} build-pr-doc
  "Generate the PR documentation markdown for a compliance fix.
   Pure function — returns the markdown string."
  [branch category title patched-files violations-fixed auto-violations]
  (let [file-count (count patched-files)]
    (str "# fix: [" category "] " title " compliance pass\n"
         "\n"
         "**Branch:** `" branch "`\n"
         "**Date:** " (today-str) "\n"
         "\n"
         "---\n"
         "```yaml\n"
         "generated-by: miniforge-compliance-scanner\n"
         "rule-id: " category "\n"
         "rule-title: \"" title "\"\n"
         "fix-type: mechanical\n"
         "violations-fixed: " violations-fixed "\n"
         "files-changed: " file-count "\n"
         "date: " (today-str) "\n"
         "```\n"
         "---\n"
         "\n"
         "## Summary\n"
         "\n"
         "Automated compliance pass applying mechanical fixes for **" title "** (Dewey " category ").\n"
         violations-fixed " violation" (when (> violations-fixed 1) "s")
         " fixed across " file-count " file" (when (> file-count 1) "s") ".\n"
         "\n"
         "## Files Changed\n"
         "\n"
         "| File | Line | Current | Suggested |\n"
         "|------|------|---------|-----------|\n"
         (str/join "\n" (map format-violation-line auto-violations))
         "\n"
         "\n"
         "## Verification\n"
         "\n"
         "- Re-run `bb miniforge run docs/compliance/miniforge-scan.md` to confirm zero violations for this rule\n"
         "- All fixes are mechanical — no semantic changes\n"
         "\n"
         "---\n"
         "*Auto-generated by the Miniforge compliance scanner.*\n")))

(defn ^{:stratum 1} build-pr-body
  "Generate the GitHub PR body with YAML attribution frontmatter."
  [category title violations-fixed file-count pr-doc-path]
  (str "```yaml\n"
       "generated-by: miniforge-compliance-scanner\n"
       "rule-id: " category "\n"
       "rule-title: \"" title "\"\n"
       "fix-type: mechanical\n"
       "violations-fixed: " violations-fixed "\n"
       "files-changed: " file-count "\n"
       "date: " (today-str) "\n"
       "```\n"
       "\n"
       "Applies mechanical fixes for all auto-fixable violations of this rule.\n"
       "Violations requiring semantic review are excluded — see the work spec\n"
       "at `docs/compliance/` for the full list.\n"
       "\n"
       "PR documentation: [`" pr-doc-path "`](" pr-doc-path ")\n"
       "\n"
       "🤖 Generated with [Miniforge](https://miniforge.ai)"))
