;; Title: Miniforge.ai
;; Subtitle: An agentic SDLC / fleet-control platform
;; Author: Christopher Lester
;; Line: Founder, Miniforge.ai (project)
;; Copyright 2025-2026 Christopher Lester (christopher@miniforge.ai)
;;
;; Licensed under the Apache License, Version 2.0 (the "License");
;; you may not use this file except in compliance with the License.
;; You may obtain a copy of the License at
;;
;;     http://www.apache.org/licenses/LICENSE-2.0
;;
;; Unless required by applicable law or agreed to in writing, software
;; distributed under the License is distributed on an "AS IS" BASIS,
;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;; See the License for the specific language governing permissions and
;; limitations under the License.

(ns commit-budget
  "Hard ceiling on staged-diff size at commit time — the fix for agents
   producing 4k-line monoliths. Counts insertions+deletions across
   staged source files, excludes generated/audit-trail content, and
   blocks the commit when the total exceeds the budget.

   Default: 200 lines. Override via env var
   `MINIFORGE_COMMIT_BUDGET_OVERRIDE=\"<rationale>\"` (the rationale is
   echoed to stdout so the override is auditable in CI logs)."
  (:require [babashka.process :as p]
            [clojure.string :as str]))

;; ----------------------------------------------------------------- Layer 0
;; pure helpers (no in-namespace deps)

(def default-budget
  "Hard ceiling on insertions+deletions per commit. 200 lines is the
   lower bound from review-throughput research (`Smartbear 2010`,
   replicated in `Cisco code review study 2018`): reviewer
   defect-detection drops sharply past ~200 LOC and stays low through
   400. Picking the lower bound forces small slices."
  200)

(def excluded-path-patterns
  "Regex patterns for files whose line-count should NOT count against
   the budget. Generated content, audit trails, lockfiles, and
   submodule pointers are all legitimate large diffs that don't
   benefit from human review."
  [#"(?i)^.*lock(?:file)?(?:\.json)?$"          ; package-lock, deps.lock
   #"(?i)^.*\.sum$"                              ; go.sum etc.
   #"(?i)^docs/pull-requests/.*\.md$"            ; auto-generated by compliance scanner
   #"(?i)^docs/standards/.*-baseline\.md$"       ; audit baseline reports
   #"(?i)(^|/)CHANGELOG\.md$"                    ; auto-rolled changelogs
   #"(?i)(^|/)\.standards$"                      ; submodule pointer
   #"(?i)(^|/)work/(done|archive)/.*"            ; archived work specs
   #"(?i)\.miniforge/.*"                         ; runtime cache
   #"(?i)\.claude/worktrees/.*"])                ; nested worktree dirs

(defn excluded?
  "True when `path` matches any pattern in `excluded-path-patterns`."
  [path]
  (boolean (some #(re-find % path) excluded-path-patterns)))

(defn parse-numstat-line
  "Parse one line of `git diff --cached --numstat` output:

       <added>\\t<deleted>\\t<path>

   Binary files report `-` for both counts; treat those as 0 (a
   binary file isn't reviewed line-by-line anyway). Returns
   `{:path String :added long :deleted long}`."
  [line]
  (let [[added deleted path] (str/split line #"\t" 3)
        ->n (fn [s] (if (= s "-") 0 (Long/parseLong s)))]
    {:path    path
     :added   (->n added)
     :deleted (->n deleted)}))

(defn reportable-changes
  "Filter the parsed numstat entries down to the ones that count
   against the budget."
  [entries]
  (remove (comp excluded? :path) entries))

(defn total-lines
  "Sum insertions+deletions across `entries`."
  [entries]
  (reduce (fn [acc {:keys [added deleted]}]
            (+ acc added deleted))
          0
          entries))

;; ----------------------------------------------------------------- Layer 1
;; git wrapper (composes Layer 0)

(defn staged-numstat
  "Return the parsed `git diff --cached --numstat` for the current
   index. Returns an empty vec if there is no staged content."
  []
  (let [{:keys [out exit]} (p/sh ["git" "diff" "--cached" "--numstat"]
                                 {:out :string :err :string})]
    (if (zero? exit)
      (->> (str/split-lines (or out ""))
           (remove str/blank?)
           (mapv parse-numstat-line))
      [])))

(defn override-rationale
  "Read the override rationale from the env var, or nil when none set."
  []
  (some-> (System/getenv "MINIFORGE_COMMIT_BUDGET_OVERRIDE")
          str/trim
          not-empty))

;; ----------------------------------------------------------------- Layer 2
;; report (composes Layer 1)

(defn print-report!
  "Emit a human-readable summary of which files contributed to the
   total + which were excluded. Helps the operator see whether the
   exclusion list missed something legitimate."
  [reportable excluded total]
  (println (format "  Reportable lines: %d (insertions + deletions)" total))
  (when (seq reportable)
    (println "  Files counted:")
    (doseq [{:keys [path added deleted]} (sort-by (comp - #(+ (:added %) (:deleted %))) reportable)]
      (println (format "    %5d  %s" (+ added deleted) path))))
  (when (seq excluded)
    (println "  Files excluded from budget:")
    (doseq [{:keys [path added deleted]} (sort-by (comp - #(+ (:added %) (:deleted %))) excluded)]
      (println (format "    %5d  %s" (+ added deleted) path)))))

;; ----------------------------------------------------------------- Layer 3
;; CLI entry (composes Layer 2)

(defn check-commit-budget!
  "Pre-commit gate. Returns nil when within budget; calls
   `(System/exit 1)` only on hard failure so it composes inside the
   `bb pre-commit` `:depends` chain (a `(System/exit 0)` here would
   terminate the JVM before lint/fmt/test got to run).

   - With no staged content, succeeds silently (lets git itself emit
     the 'nothing to commit' message).
   - With `MINIFORGE_COMMIT_BUDGET_OVERRIDE` set, succeeds and echoes
     the rationale.
   - Otherwise prints a per-file breakdown and the verdict."
  [budget]
  (let [entries     (staged-numstat)
        excluded    (filter (comp excluded? :path) entries)
        reportable  (reportable-changes entries)
        total       (total-lines reportable)
        rationale   (override-rationale)]
    (cond
      (empty? entries)
      (println "📏 commit-budget: no staged content")

      rationale
      (do (println (format "📏 commit-budget: OVERRIDDEN (%d reportable lines)" total))
          (println (str "  rationale: " rationale))
          (when (> total budget)
            (println (format "  WARNING: %d > %d — budget intentionally bypassed."
                             total budget)))
          (print-report! reportable excluded total))

      (<= total budget)
      (println (format "📏 commit-budget: %d / %d lines OK" total budget))

      :else
      (do (println "")
          (println "════════════════════════════════════════════════════════════════")
          (println (format "❌ COMMIT BUDGET EXCEEDED: %d > %d lines" total budget))
          (println "════════════════════════════════════════════════════════════════")
          (println "")
          (print-report! reportable excluded total)
          (println "")
          (println "Why this exists:")
          (println "  Reviewer defect-detection drops sharply past ~200 LOC.")
          (println "  Slicing a large change into a stack of small commits keeps")
          (println "  each one reviewable; the agent that merges first is still on")
          (println "  the way to the same destination.")
          (println "")
          (println "How to proceed:")
          (println "  • Slice the work: stage only the files for the first PR,")
          (println "    commit, then continue with the next slice.")
          (println "  • Genuine exception (lockfile rev, generated migration):")
          (println "    MINIFORGE_COMMIT_BUDGET_OVERRIDE='<rationale>' git commit ...")
          (println "    The rationale is echoed in the commit log for review.")
          (println "")
          (System/exit 1)))))

(defn run [_opts]
  (check-commit-budget! default-budget))
