#!/usr/bin/env bb
;; Generate a test-only workflow spec for the phase files

(require '[clojure.java.io :as io]
         '[clojure.edn :as edn]
         '[clojure.string :as str])

(defn read-file-content [path]
  (slurp (io/file path)))

(defn create-workflow-spec []
  (let [base-path "components/phase/src/ai/miniforge/phase"
        files [{:name "verify.clj"
                :path (str base-path "/verify.clj")}
               {:name "review.clj"
                :path (str base-path "/review.clj")}
               {:name "release.clj"
                :path (str base-path "/release.clj")}]
        code-files (mapv (fn [{:keys [name path]}]
                           {:path path
                            :content (read-file-content path)
                            :action :test-existing})
                         files)
        spec {:workflow/spec-version "1.0.0"
              ;; Use test-only workflow for generating tests
              :workflow/type :test-only
              :workflow/version "2.0.0"

              ;; Top-level workflow metadata
              :title "Test Generation for Phase Files"
              :description "Generate comprehensive tests for phase interceptors"

              ;; Task specification
              :task/title "Generate tests for miniforge-generated phase files"
              :task/description
              "Create comprehensive tests for the verify, review, and release phase
               interceptors that were autonomously generated by miniforge during the
               meta-meta loop bootstrap session."

              :task/intent
              "Generate unit and integration tests that verify:
               - Phase lifecycle (enter, leave, error handlers)
               - Agent invocation and result handling
               - Metrics tracking and aggregation into execution metrics
               - Error recovery and retry logic with budget enforcement
               - Context propagation and phase state transitions
               - Registry integration via multimethods"

              :task/constraints
              ["Use clojure.test framework"
               "Follow existing test patterns from plan and implement phase tests"
               "Aim for 80%+ code coverage on each file"
               "Test both happy path and error conditions"
               "Mock agent invocations to avoid LLM calls"
               "Mock registry functions where needed"
               "Test files should be: test/ai/miniforge/phase/*_test.clj"
               "Include integration tests for full phase execution cycles"]

              :task/code-artifact
              {:code/id (random-uuid)
               :code/language "clojure"
               :code/summary "Phase interceptor implementations generated by miniforge"
               :code/files code-files}

              :task/acceptance-criteria
              ["Tests cover all public and private functions in each file"
               "Tests verify proper agent creation and invocation"
               "Tests verify metrics are correctly calculated and merged"
               "Tests verify error handling triggers retries within budget"
               "Tests verify phase state transitions (pending -> running -> completed/failed)"
               "Tests verify registry integration works correctly"
               "Tests use mocks to avoid external dependencies"
               "All generated tests pass when run"
               "Test coverage meets 80% threshold for each file"]}]
    (spit "examples/workflows/test-phase-files.edn"
          (with-out-str
            (clojure.pprint/pprint spec)))
    (println "✓ Generated examples/workflows/test-phase-files.edn")))

(create-workflow-spec)
