(ns ai.miniforge.release-executor.metadata-test
  (:require
   [ai.miniforge.release-executor.metadata :as metadata]
   [clojure.string :as str]
   [clojure.test :refer [deftest is testing]]))

(deftest slugify-uses-message-defaults
  (testing "nil input falls back to the configured default slug seed"
    (is (= "change" (metadata/slugify nil)))))

(deftest fallback-release-metadata-renders-resource-backed-body
  (testing "fallback metadata uses the release-executor message catalog"
    (let [result (metadata/fallback-release-metadata
                  "Add release metadata strings"
                  [{:code/files [{:path "src/feature.clj" :action :create}
                                 {:path "README.md" :action :modify}]}])
          body (:release/pr-body result)]
      (is (= "Add release metadata strings" (:release/commit-message result)))
      (is (str/includes? body "## Summary\n\nAdd release metadata strings\n\n"))
      (is (str/includes? body "## Changes\n\n- `src/feature.clj` (create)\n- `README.md` (modify)\n\n"))
      (is (str/includes? body "## Test plan\n\n- [ ] Verify changes compile and tests pass\n- [ ] Review generated code for correctness\n\n"))
      (is (str/ends-with? body "---\nGenerated by Miniforge SDLC workflow (2 files)")))))

(deftest fallback-release-metadata-uses-default-description
  (testing "fallback metadata uses the configured default description when none is provided"
    (let [result (metadata/fallback-release-metadata nil [{:code/files []}])
          body (:release/pr-body result)]
      (is (= "implement changes" (:release/commit-message result)))
      (is (not (str/includes? body "## Changes")))
      (is (str/starts-with? body "## Summary\n\nimplement changes\n\n"))
      (is (str/ends-with? body "---\nGenerated by Miniforge SDLC workflow (0 files)")))))
